---
- name: "Check if Azure CLI is already installed"
  stat:
    path: /usr/bin/az
  register: azcli_installed

- name: "Download & Install Azure CLI repo"
  when: not azcli_installed.stat.exists
  block:
    - name: "Retrieve the key for the Microsoft apt repository"
      get_url:
        url: " https://packages.microsoft.com/keys/microsoft.asc "
        dest: /tmp/microsoft.asc
    - name: "Add the Microsoft apt repository key"
      shell: "gpg --dearmor --output /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc"
      args:
        creates: "/usr/share/keyrings/microsoft.gpg"
    - name: "Get distribution release"
      set_fact:
        AZ_REPO: "{{ ansible_distribution_release }}"
    - name: "Add the Microsoft azure-cli apt repository"
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ AZ_REPO }} main"
        state: present
    - name: "Install Azure CLI"
      apt:
        name: "azure-cli"
        state: present
        update_cache: yes
    - name: "Cleanup"
      file:
        path: /tmp/microsoft.asc
        state: absent
  become: true
  become_method: sudo